i3a=0
i3b=0
print()
print("                                                         Welcome to the Disney section!")
print()
print("Question 1")
print()
print("In the Disney story the ‘The Little Mermaid’ which of the following is not Triton’s daughter?")
print("1. Andrina")
print("2. Attina")
print("3. Adora")
print("4. Allana")
a3a=int(input("Enter the option number: "))
print()
if a3a==3:
    print("Your answer is Correct!")
    print("Attina, Alana, Adella, Aquata, Arista, and Andrina first appear in the original film, introduced during the 'Daughters of Triton' sequence.")
    i3a=i3a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 3!")
    print("Attina, Alana, Adella, Aquata, Arista, and Andrina first appear in the original film, introduced during the 'Daughters of Triton' sequence.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 2")
print()
print("What had Cinderella left behind at the ball?")
print("1. Ring")
print("2. Glass shoe")
print("3. Scarf")
print("4. Tiara")
a3a=int(input("Enter the option number: "))
print()
if a3a==2:
    print("Your answer is Correct!")
    print("As Cinderella dances with the prince, she loses track of time and must leave the ball. Fleeing away from the ball and the prince, one of her glass slippers falls.")
    i3a=i3a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 2!")
    print("As Cinderella dances with the prince, she loses track of time and must leave the ball. Fleeing away from the ball and the prince, one of her glass slippers falls.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 3")
print()
print("  How many brothers did the character Hans have in Frozen?")
print("1. 5")
print("2. 10")
print("3. 12")
print("4. 6")
a3a=int(input("Enter the option number: "))
print()
if a3a==3:
    print("Your answer is Correct!")
    print("Hans had 12 brothers.")
    i3a=i3a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 3!")
    print("Hans had 12 brothers.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 4")
print()
print(" In the Disney story the Princess and the Frog, which fictional country does the prince Naveen come from?")
print("1. Maldonia")
print("2. Marca")
print("3. Mypos")
print("4. Maramargos")
a3a=int(input("Enter the option number: "))
print()
if a3a==1:
    print("Your answer is Correct!")
    print("Prince Naveen is native to the kingdom of Maldonia, where he lives alongside his parents, the king and queen , and his younger brother, Prince Ralphie.")
    i3a=i3a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 1!")
    print("Prince Naveen is native to the kingdom of Maldonia, where he lives alongside his parents, the king and queen , and his younger brother, Prince Ralphie.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 5")
print()
print("For how many years did the Genie in Aladdin say, he got trapped in the lamp?")
print("1. 100 years")
print("2. 10,000 years")
print("3. 1000 years")
print("4. 500 years")
a3a=int(input("Enter the option number: "))
print()
if a3a==2:
    print("Your answer is Correct!")
    print("Genie was originally a slave imprisoned within his lamp, which, itself, was sealed away in the Cave of Wonders for 10,000 years.")
    i3a=i3a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 2!")
    print("Genie was originally a slave imprisoned within his lamp, which, itself, was sealed away in the Cave of Wonders for 10,000 years.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 6")
print()
print("How many puppies did Perdita give birth to in the Disney story ‘101 Dalmatians’? ")
print("1. 9")
print("2. 101")
print("3. 15")
print("4. 12")
a3a=int(input("Enter the option number: "))
print()
if a3a==3:
    print("Your answer is Correct!")
    print("Even though Perdita gave birth to 15 puppies, the only names noted in the film were: Lucky, Rolly, Patch, Penny, Pepper, and Freckles.")
    i3a=i3a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 3!")
    print("Even though Perdita gave birth to 15 puppies, the only names noted in the film were: Lucky, Rolly, Patch, Penny, Pepper, and Freckles.")
print()
input("Press enter any to continue to the next question")
print()
print()
print("Question 7")
print()
print(" Why did Elsa stay with her mother’s people in Frozen 2?")
print("1. To protect the Enchanted Forest")
print("2. To hide from the crowds")
print("3. To sing her favorite songs")
print("4. None of the above")
a3a=int(input("Enter the option number: "))
print()
if a3a==1:
    print("Your answer is Correct!")
    print("Elsa stayed with her mother's people to protect the enchanted forest.")
    i3a=i3a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 2!")
    print("Elsa stayed with her mother's people to protect the enchanted forest.") 
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 8")
print()
print("What name did Ursula, use when she became a human in ‘The Little Mermaid’?")
print("1. Vanessa")
print("2. Alexis")
print("3. Amber")
print("4. Cathy")
a3a=int(input("Enter the option number: "))
print()
if a3a==1:
    print("Your answer is Correct!")
    print("Angered that Ariel almost succeeded, Ursula transforms herself into a beautiful human woman named Vanessa.") 
    i3a=i3a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 1!")
    print("Angered that Ariel almost succeeded, Ursula transforms herself into a beautiful human woman named Vanessa.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 9")
print()
print("What was the name of Merlyn’s pet owl, in the Disney story The Sword in the Stone?")
print("1. Aristotle")
print("2. Socrates")
print("3. Plato")
print("4. Archimedes")
a3a=int(input("Enter the option number: "))
print()
if a3a==4:
    print("Your answer is Correct!")
    print("Junius Matthews as Archimedes, Merlin's crotchety, yet highly educated, pet owl and servant, who has the ability to speak.") 
    i3a=i3a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 4!")
    print("Junius Matthews as Archimedes, Merlin's crotchety, yet highly educated, pet owl and servant, who has the ability to speak.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 10")
print()
print("What was the name of Maleficient’s pet raven, in Sleeping Beauty?")
print("1. Diablo")
print("2. Diable")
print("3. Mauvais")
print("4. Malcom")
a3a=int(input("Enter the option number: "))
print()
if a3a==1:
    print("Your answer is Correct!")
    print("Diablo is Maleficent's pet raven. ") 
    i3a=i3a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 1!")
    print("Diablo is Maleficent's pet raven.")
print()
print("Your scores in the MCQ segment is",i3a,"out of 10!")
print()
input("Press enter to proceed to the Fill in the blanks segment.")
print()
print("Question 1")
print()
print("What is the name of Wendy’s dog in Peter Pan?")
a3b=input("Enter your answer: ")
if a3b=="Nana"or a3b=="nana":
     print("Your answer is correct!")
     i3b=i3b+1
else:
     print("Your answer is incorrect!")
     print("The correct answer is Nana.")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 2")
print()
print(" What is the name of Andy’s neighbor in Toy Story?")
a3b=input("Enter your answer: ")
print()
if a3b=="Sid" or a3b=="sid":
     print("Your answer is correct!")
     i3b=i3b+1
else:
     print("Your answer is incorrect!")
     print("The correct answer is Sid.")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 3")
print()
print("Which Disney Princess sings “Once Upon a Dream”?")
a3b=input("Enter your answer: ")
print()
if a3b=="Aurora"or a3b=="aurora":
     print("Your answer is correct!")
     i3b=i3b+1
else:
     print("Your answer is incorrect!")
     print("The correct answer is Aurora (Sleeping Beauty).")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 4")
print()
print("What was the first Pixar movie? ")
a3b=input("Enter your answer: ")
print()
if a3b=="Toys Story"or a3b=="toy story"or a3b=="toystory":
     print("Your answer is correct!")
     i3b=i3b+1
else:
     print("Your answer is incorrect!")
     print("The correct answer is Toy Story.")
      
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 5")
print()
print("Rapunzel’s chameleon in Tangled is called what?")
a3b=input("Enter your answer: ")
print()
if a3b=="Pascal"or a3b=="pascal":
     print("Your answer is correct!")
     i3b=i3b+1
else:
     print("Your answer is incorrect!")
     print("The correct answer is Pascal.")
print()
print("Your scores in the Fill in the blanks segment is",i3b,"out of 15!")
print()
print("Your total score is",i3a+i3b,"out of 25!")
print()
print("The trivia is over!")
print("Thank You")

