i7a=0
i7b=0
print()
print("                                                         Welcome to the Entertainment section!")
print()
print("Question 1")
print()
print("Which of the following movies won the Oscar awards 2020 for Best Picture?")
print("1. Once Upon a Time in Hollywood")
print("2. Joker")
print("3. Judy")
print("4. Parasite")
a7a=int(input("Enter the option number: "))
print()
if a7a==4:
    print("Your answer is Correct!")
    print("Parasite won the Oscar Awards for Best Picture.It is the first time that a South Korean movie has won the International Feature Film Category in the History of the Oscars.")
    i7a=i7a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 4!")
    print("Parasite won the Oscar Awards for Best Picture.It is the first time that a South Korean movie has won the International Feature Film Category in the History of the Oscars.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 2")
print()
print("Who played the character of Allauddin Khilji in the controversial movie 'Padmavat'?")
print("1. Shahid Kapoor")
print("2. Ranveer Singh")
print("3. Ranbir Kapoor")
print("4. Rana Daggubati")
a7a=int(input("Enter the option number: "))
print()
if a7a==2:
    print("Your answer is Correct!")
    print("Ranveer Singh played the character of Allauddin Khilji in the controversial movie 'Padmavat'.")
    i7a=i7a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 2!")
    print("Ranveer Singh played the character of Allauddin Khilji in the controversial movie 'Padmavat'.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 3")
print()
print("What is the name of Malala Yousafzai's biopic?")
print("1. The Aviator")
print("2. Frida")
print("3. The social network")
print("4. Gul Makai")
a7a=int(input("Enter the option number: "))
print()
if a7a==4:
    print("Your answer is Correct!")
    print("Gul Makai is a biographical drama of Malala Yousafzai.It was directed by H.E Amjad Khan.")
    i7a=i7a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 4!")
    print("Gul Makai is a biographical drama of Malala Yousafzai.It was directed by H.E Amjad Khan.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 4")
print()
print("Which Hindi movie is based on the Indian hockey team on their first Olympic gold since India became independent?")
print("1. Lagaan")
print("2. MS Dhoni")
print("3. Gold")
print("4. Chak De")
a7a=int(input("Enter the option number: "))
print()
if a7a==3:
    print("Your answer is Correct!")
    print("Gold: The Dream That United Our Nation is a Hindi movie based on the Indian hockey team on their first Olympic gold since India became independent.")
    i7a=i7a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 3!")
    print("Gold: The Dream That United Our Nation is a Hindi movie based on the Indian hockey team on their first Olympic gold since India became independent.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 5")
print()
print("In the movie 'Wonder Woman', who plays the role of Diana/Wonder Woman?")
print("1. Gal Gadot")
print("2. Gwyneth Paltrow")
print("3. Rachel McAdams")
print("4. Scarlett Johansson")
a7a=int(input("Enter the option number: "))
print()
if a7a==1:
    print("Your answer is Correct!")
    print("'Wonder Woman' is a superhero movie based on a character from Detective Comics.The lead role of Wonder Woman is played by Gal Gadot.")
    i7a=i7a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 1!")
    print("'Wonder Woman' is a superhero movie based on a character from Detective Comics.The lead role of Wonder Woman is played by Gal Gadot.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 6")
print()
print("Name the director of the blockbuster movie 'Bahubali'.")
print("1. Prabhas")
print("2. Prabhu Deva")
print("3. S.S Rajamouli")
print("4. Karan Johar")
a7a=int(input("Enter the option number: "))
print()
if a7a==3:
    print("Your answer is Correct!")
    print("S.S. Rajamouli is the dircetor of the blockbuster movie 'Bahubali'.")
    i7a=i7a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 3!")
    print("S.S. Rajamouli is the dircetor of the blockbuster movie 'Bahubali'.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 7")
print()
print("Which Bollywood actress recieved the Padmashri award in the year 2020?")
print("1. Taapsee Pannu")
print("2. Shraddha Kapoor")
print("3. Kangana Ranaut")
print("4. Bhumi Pednekar")
a7a=int(input("Enter the option number: "))
print()
if a7a==3:
    print("Your answer is Correct!")
    print("Kangana Ranaut won the Padmashri award for her contibution in Arts.")
    i7a=i7a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 3!")
    print("Kangana Ranaut won the Padmashri award for her contibution in Arts.") 
print()
input("Press enter any key  to continue to the next question")
print()
print()
print("Question 8")
print()
print("Which is not the name of a child selected to tour the Wonka factory in Willy Wonka and the Chocolate Factory?")
print("1. Billy Warp")
print("2. Veruca Salt")
print("3. Mike Teavee")
print("4. Charlie Bucket")
a7a=int(input("Enter the option number: "))
print()
if a7a==1:
    print("Your answer is Correct!")
    i7a=i7a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 1!")
print()
input("Press enter any key  to continue to the next question")
print()
print()
print("Question 9")
print()
print("Which actor hasn’t played the Joker?")
print("1. Jack Nicholson")
print("2. Sean Penn")
print("3. Jared Leto")
print("4. Mark Hamil")
a7a=int(input("Enter the option number: "))
print()
if a7a==2:
    print("Your answer is Correct!")
    print("Sean Penn didnt play the Joker.") 
    i7a=i7a+1
else:
    print("Your answer is incorrect!")
    print()
    print("Sean Penn didnt play the Joker.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 10")
print()
print("What object was Toy Story’s Woody originally?")
print("1. A cowboy doll")
print("2. A puppet")
print("3. A clown doll")
print("4. A nesting doll")
a7a=int(input("Enter the option number: "))
print()
if a7a==1:
    print("Your answer is Correct!")
    print("Sheriff Woody is the protagonist of the Toy Story franchise. He is a vintage cowboy doll that originally belonged to a boy named Andy Davis.") 
    i7a=i7a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 1!")
    print("Sheriff Woody is the protagonist of the Toy Story franchise. He is a vintage cowboy doll that originally belonged to a boy named Andy Davis.")
print()
print("Your score in the MCQ segment is",i7a,"out of 10!")
print()
input("Press enter to proceed to the Fill in the blanks segment.")
print()
print("Question 1")
print()
print("Who is the Director of the Titanic movie?")
a7b=input("Enter your answer: ")
print()
if a7b=="James Cameron"or a7b=="james cameron":
     print("Your answer is correct!")
     i7b=i7b+1
else:
     print("Your answer is incorrect!")
     print("The correct answer is James Cameron.")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 2")
print()
print(" Dhindora is an Indian webseries, directed by which Indian Youtuber?")
a7b=input("Enter your answer: ")
print()
if a7b=="BB Ki Vines" or a7b=="Bhuvan Bam" or a7b=="bb ki vines" or a7b=="bhuvan bam":
     print("Your answer is correct!")
     i7b=i7b+1
else:
     print("Your answer is incorrect!")
     print("The correct answer is Bhuvan Bam.")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 3")
print()
print("Who played Jack in Titanic?")
a7b=input("Enter your answer: ")
print()
if a7b=="Leonardo DeCaprio"or a7b=="leonardo decaprio":
     print("Your answer is correct!")
     i7b=i7b+1
else:
     print("Your answer is incorrect!")
     print("The correct answer is Leonardo DeCaprio.")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 4")
print()
print("Which popular Indian actor starred in the movie 'Suryavanshi'? ")
a7b=input("Enter your answer: ")
print()
if a7b=="Akshay Kumar"or a7b=="akshay kumar":
     print("Your answer is correct!")
     i7b=i7b+1
else:
     print("Your answer is incorrect!")
     print("The correct answer is Akshay Kumar.")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 5")
print()
print("The famous web series 'Squid Games' belong to which country?")
a7b=input("Enter your answer: ")
print()
if a7b=="South Korea"or a7b=="south korea":
     print("Your answer is correct!")
     i7b=i7b+1
else:
     print("Your answer is incorrect!")
     print("The correct answer is South Korea.")
print()
print("Your score in the Fill in the blanks segment is",i7b,"out of 15!")
print()
print("Your total score is",i7a+i7b,"out of 25!")
print()
print("The trivia is over!")
print("Thank You")
