print()
print("                                     Welcome to the Hogwarts Express!")
print("           I hope you're ready, coz only top 0.1% harry potter fans can get full points.")
print("                                   Hope you'll enjoy this quiz ride.")
print()
print("Question 1:")
print()
print("Hogwart Express departs KIng Cross at what time?")
print()
print("1. 10 o'clock")
print("2. 11 o'clock")
print("3. 12 o'clock")
print("4.  9 o'clock")
print()
a2=int(input("Enter the option number: "))
print()
i2=0
if a2==2:
    print("Choo choo, your journey has started with a correct answer.")
    i2=i2+1
elif a2==1 or a2==4:
    print("Your answer is wrong. Due to you Harry had to wait for a long time until the train departed.")
    print()
    print("The correct answer was option 2.")
else:
    print("Your answer is wrong. Due to you Harry missed his train.")
    print()
    print("The correct answer was option 2.")
print()
input("Press enter to continue to next question")
print()
print("Question 2:")
print()
print("What was Dumbledore's boyfriend name?")
print()
print("1. Lucius Malfoy")
print("2. Rubeus Hagrid")
print("3. Gellert Grindelwald")
print("4. Severus Snape")
print()
b2=int(input("Enter the option number: "))
print()
if b2==3:
    print("Hoorah, Your answer is correct. You're up to date with the new things from Harry Potter.")
    i2=i2+1
else:
    print("Your answer is wrong.")
    print()
    print("The correct answer was option 3.")
print()
input("Press enter to continue to next question")
print()
print("Question 3: ")
print()
print("What spell did Harry use to kill Lord Voldemort?")
print()
print("1. Expelliarmus")
print("2. Expecto Patronum")
print("3. Avada Kedavra")
print("4. Accio")
print()
c2=int(input("Enter the option number: "))
print()
if c2==1:
    print("Congrats, Your answer is correct. I hope Voldemort never come back.")
    i2=i2+1
else:
    print("Your answer is wrong.")
    print()
    print("Correct answer was option 1")
    print()
    print("Voldemort dies in the final epic battle. Harry destroys him by the spell 'EXPELLIARMUS'.")
print()
input("Press enter to continue to next question")
print()
print("Question 4:")
print()
print("Who kills Voldemort's snake?")
print()
print("1. Harry Potter")
print("2. Ron Weasley")
print("3. Hermione Granger")
print("4. Neville Longbottom")
print()
d2=int(input("Enter the option here: "))
print()
if d2==4:
    print("Your answer is correct.")
    i2=i2+1
    print()
    print("Who knew Longbottom was gonna be such an important character in Harry Potter's universe.")
else:
    print("Your answer is wrong.")
    print()
    print("The correct answer was option 4")
    print()
    print("Neville Longbottom kills Voldemort's Snake, destroying the last hocrux of voldemort. He teaches us to never underestimate a person.")
print()
input("Press enter to continue to next question")
print()
print("Question 5:")
print()
print("‘Wit beyond measure is man’s greatest treasure’ is the motto of which house?")
print()
print("1. Gryffindor")
print("2. Hufflepuff")
print("3. Ravenclaw")
print("4. Slytherin")
print()
e2=int(input("Enter your option here: "))
print()
if e2==3:
    print("Your answer is correct.")
    i2=i2+1
    print()
    print("Welcome to Ravenclaw.")
else:
    print("Your answer was incorrect.")
    print()
    print("The correct answer was option 3")
    print()
    print("I guess you're a friend of Draco Malfoy. JK")
print()
input("Press enter to continue to next question")
print()
print("Question 6:")
print()
print("What magical talent does Harry share with Voldemort?")
print()
print("1. Being an Animagus")
print("2. Being a Parselmouth")
print("3. Being an Auror")
print("4. Being a Death Eater")
print()
f2=int(input("Enter your option here: "))
print()
if f2==2:
    print("You got this right.")
    i2=i2+1
    print()
    print("One of my fav scene is when he brakes the glass bcz he heard the thoughts of the snake.")
else:
    print("You are incorrect.")
    print()
    print("The correct answer was option 2")
    print()
    print("Harry was capable of talking with snakes just like Voldemort.")
print()
input("Press enter to continue to next question")
print()
print("Question 7:")
print()
print("The tears of which animal are the only known antidote to basilisk venom?")
print()
print("1. Phoenix")
print("2. Billywig")
print("3. Hippogriff")
print("4. Boggart")
print()
g2=int(input("Enter your option here: "))
print()
if g2==1:
    print("Your answer is incorrect. Jk It's correct.")
    i2=i2+1
    print()
    print("Just don't spook the phoenix.")
else:
    print('Your answer is incorrect.')
    print()
    print("The correct option was 1")
    print()
    print("Phoenix is a bird which turns into ash when die, and rebirth from the same ash.")
print()
input("Press enter to continue to next question")
print()
print("Question 8:")
print()
print("What position does Harry play on his Quidditch team?")
print()
print("1. Chaser")
print("2. Keeper")
print("3. Bludger")
print("4. Seeker")
print()
h2=int(input("Enter your option here: "))
print()
if h2==4:
    print("Your answer is correct")
    i2=i2+1
    print()
    print("Hope you don't get chased by an evil ball.")
else:
    print("Your answer is incorrect")
    print()
    print("The correct option was 4")
    print()
    print("It's just a game of basketball with flying brooms, magic and a tiny naughty goldenfinch")
print()
input("Press enter to continue to next question")
print()
print("Question 9:")
print()
print("Finish the inscription on Dobby’s tombstone: ‘Here lies Dobby…")
print()
print("1. ‘A true friend’")
print("2. ‘The best servant’")
print("3. ‘A free Elf’")
print("4. ‘Master of socks’")
print()
j2=int(input("Enter your option here: "))
print()
if j2==3:
    print("Your answer is correct")
    i2=i2+1
    print()
    print("I don't know about you but i mourned dobby for 3 days and still get sad when i think about him.")
else:
    print("Your option is incorrect.")
    print()
    print("The correct answer was option 3")
    print()
    print("Please rewatch the whole movie!")
print()
input("Press enter to continue to next question")
print()
print("Question 10:")
print()
print("Who saved a centaur from being strangled by Professor Umbridge in the Forbidden Forest?")
print()
print("1. Grawp")
print("2. Buckbeak")
print("3. Hagrid")
print("4. Luna")
print()
k2=int(input("Enter you option here: "))
print()
if k2==1:
    print("Your answer is correct.")
    i2=i2+1
    print()
    print("This was a tough question, I guess you're a true fan of Harry potter.")
else:
    print('Your answer is incorrect')
    print()
    print("The correct answer was option 4")
    print()
    print("FYI Centaur is an animal which is half human and half horse.")
print()
print("Here Completes your MCQ part.")
print()
input("Press enter to continue.")
print()
print("This is your typing part which is worth 3 points.")
print()
input("Press enter to continue to next question")
print()
print("Question 11: ")
print()
print("What is the name of Harry Potter's owl?")
print()
l2=input("Enter your answer here: ")
print()
if l2=="Hedwig" or l2=="hedwig" or l2=="HEDWIG":
    print("Your answer is correct")
    i2=i2+3
else:
    print("Yor answer is incorrect.")
    print()
    print("The correct answer is hedwig.")
print()
input("Press enter to continue to next question")
print()
print("Question 12:")
print()
print("Who is Draco Malfoy's dad?")
print()
m2=input("Enter your answer here (full name): ")
print()
if m2=="Lucius Malfoy" or m2=="lucius malfoy" or m2=="Lucius malfoy" or m2=="lucius Malfoy" or m2=="LUCIUS MALFOY":
    print("Your answer is correct")
    i2=i2+3
else:
    print("Your answer is incorrect.")
    print()
    print("The correct answer is Lucius Malfoy.")
print()
input("Press enter to continue to next question")
print()
print("Question 13:")
print()
print("Who killed Dobby by throwing a knife at him?")
print()
n2=input("Enter your answer here (Full name): ")
print()
if n2=="Bellatrix Lestrange" or n2=="Bellatrix lestrange" or n2=="bellatrix Lestrange" or n2=="bellatrix lestrange" or n2=="BELLATRIX LESTRANGE":
    print("Your answer is correct")
    i2=i2+3
else:
    print("Your answer is incorrect.")
    print()
    print("The correct answer is Bellatrix Lestrange.")
print()
input("Press enter to continue to next question")
print()
print("Question 14:")
print()
print("Name the killing curse.")
print()
o2=input("Enter your answer here: ")
print()
if o2=="Avada Kedavra" or o2=="avada Kedavra" or o2=="Avada kedavra" or o2=="avada kedavra" or o2=="AVADA KEDAVRA":
    print("Your answer is correct")
    i2=i2+3
else:
    print("Your answer is incorrect.")
    print()
    print("The correct answer is Avada Kedavra.")
print()
input("Press enter to continue to next question")
print()
print("Question 15:")
print()
print("What relation was Sirius Black to Harry?")
print()
p2=input("Enter your answer here: ")
print()
if p2=="Godfather" or p2=="godfather" or p2=="GODFATHER":
    print("Your answer is correct")
    i2=i2+3
else:
    print("Yor answer is incorrect.")
    print()
    print("The correct answer is Godfather.")
print()
print("                          Thank you for attending Harry Potter's quiz.")
print()
print("                                      Your score is", i2)
print()
print("                                     Have a great day")