print()
print("                                     Welcome to Human Rights Quiz!")
print("                            This will test your knowledge on HUman Rights.")
print("                           Hope you'll enjoy this quiz and learn new things.")
print()
print("Question 1:")
print()
print("Poor mental health increases the risk for long-lasting (chronic) physical conditions like")
print()
print("1. heart disease")
print("2. stroke")
print("3. cancer")
print("4. all of the above")
print()
a8=int(input("Enter the option number: "))
print()
i8=0
if a8==4:
    print("Your answer is correct.")
    i8=i8+1
else:
    print("Your answer is wrong.")
    print()
    print("The correct answer was option 4.")
print()
input("Press enter to continue to next question")
print()
print("Question 2:")
print()
print("Suicide is the ________ leading cause of death among people ages 15-34 in the United States.")
print()
print("1. 24th")
print("2. 10th")
print("3. 2nd")
print("4. 40th")
print()
b8=int(input("Enter the option number: "))
print()
if b8==3:
    print("Your answer is correct.")
    i8=i8+1
else:
    print("Your answer is wrong.")
    print()
    print("The correct answer was option 3.")
print()
input("Press enter to continue to next question")
print()
print("Question 3: ")
print()
print("How are individuals with eating disorders affected?")
print()
print("1. They only want to eat unhealthy foods")
print("2. They are obsessed with planning meals weeks in advance")
print("3. They have anxieties about their relationship with food and weight")
print("4. They are concerned with eating only things they can afford")
print()
c8=int(input("Enter the option number: "))
print()
if c8==3:
    print("Your answer is correct.")
    i8=i8+1
else:
    print("Your answer is wrong.")
    print()
    print("The correct answer was option 3.")
print()
input("Press enter to continue to next question")
print()
print("Question 4:")
print()
print("Which of these is NOT classed as a symptom of having a mental health problem?")
print()
print("1. Self-harm")
print("2. Low self esteem")
print("3. social withdrawal")
print("4. broken bones")
print()
d8=int(input("Enter the option here: "))
print()
if d8==4:
    print("Your answer is correct.")
    i8=i8+1
else:
    print("Your answer is wrong.")
    print()
    print("The correct answer was option 4.")
print()
input("Press enter to continue to next question")
print()
print("Question 5:")
print()
print("If you are having a conversation about someone's mental health, what should you NOT do?")
print()
print("1. Reassure the person")
print("2. Tell them you will talk to other people about it")
print("3. Ask simple questions and encourage them to share")
print("4. Choose an appropriate place that makes them feel relaxed")
print()
e8=int(input("Enter your option here: "))
print()
if e8==2:
    print("Your answer is correct.")
    i8=i8+1
else:
    print("Your answer was incorrect.")
    print()
    print("The correct answer was option 2.")
print()
input("Press enter to continue to next question")
print()
print("Question 6:")
print()
print("How might you help a person with a mental health issue in terms of workplace relationships?")
print()
print("1. Promote tolerance, understanding and positive relationships between all staff member.")
print("2. Isolate said person so they are not bothered by other people")
print("3. Limit the amount of help that managers can give to them")
print("4. Tell others to totally ignore the fact that they are suffering from a mental health problem")
print()
f8=int(input("Enter your option here: "))
print()
if f8==1:
    print("Your answer is correct.")
    i8=i8+1
else:
    print("Your answer was incorrect.")
    print()
    print("The correct answer was option 1.")
print()
input("Press enter to continue to next question")
print()
print("Question 7:")
print()
print("How many kids have a mental health disorder?")
print()
print("1. 3%")
print("2. 7%")
print("3. 16.5%")
print("4. 23%")
print()
g8=int(input("Enter your option here: "))
print()
if g8==3:
    print("Your answer is correct.")
    i8=i8+1
else:
    print("Your answer was incorrect.")
    print()
    print("The correct answer was option 3.")
print()
input("Press enter to continue to next question")
print()
print("Question 8:")
print()
print("The seminal Nicklinson case revealed tensions between the Suicide Act 1961 and which Convention right?What are some common symptoms of alcohol abuse?")
print()
print("1. Extreme mood swings, including irritability and rage")
print("2. Drinking alone or hiding alcohol consumption")
print("3. Social isolation or a change in acquaintances")
print("4. All of the above")
print()
h8=int(input("Enter your option here: "))
print()
if h8==4:
    print("Your answer is correct.")
    i8=i8+1
else:
    print("Your answer is wrong.")
    print()
    print("The correct answer was option 4.")
print()
input("Press enter to continue to next question")
print()
print("Question 9:")
print()
print("What causes mental illness?")
print()
print("1. Heredity, including gene abnormalities")
print("2. Childhood or adult trauma")
print("3. Lifestyle choices, such as substance abuse or poor dietary habits")
print("4. All of the above")
print()
j8=int(input("Enter your option here: "))
print()
if j8==4:
    print("Your answer is correct.")
    i8=i8+1
else:
    print("Your answer was incorrect.")
    print()
    print("The correct answer was option 4.")
print()
input("Press enter to continue to next question")
print()
print("Question 10:")
print()
print("What is the cause of Post-Traumatic Stress Disorder (PTSD)?")
print()
print("1. It often occurs after an event which you felt seriously endangered at the time and you might die.")
print("2. It occurs after a stressful day at work.")
print("3. It occurs in all people with anxiety. ")
print("4. There is no known cause.")
print()
k8=int(input("Enter you option here: "))
print()
if k8==1:
    print("Your answer is correct.")
    i8=i8+1
else:
    print("Your answer was incorrect.")
    print()
    print("The correct answer was option 1.")
print()
print("Here Completes your MCQ part.")
print()
input("Press enter to continue.")
print()
print("This is your typing part which is worth 3 points.")
print()
input("Press enter to continue to next question")
print()
print("Question 11: ")
print()
print("Which country’s Prime Minister was re-elected in 2001 after publicly taking time off for depression?")
print()
l8=input("Enter your answer here: ")
print()
if l8=="Norway" or l8=="norway" or l8=="NORWAY":
    print("Your answer is correct")
    i8=i8+3
else:
    print("Yor answer is incorrect.")
    print()
    print("The correct answer is Norway.")
print()
input("Press enter to continue to next question")
print()
print("Question 12:")
print()
print("What is the leading cause of disability worldwide and is a major contributor to the global burden of disease?")
print()
m8=input("Enter your answer here: ")
print()
if m8=="Depression" or m8=="despression" or m8=="DEPRESSION":
    print("Your answer is correct")
    i8=i8+3
else:
    print("Your answer is incorrect.")
    print()
    print("The correct answer is Depression.")
print()
input("Press enter to continue to next question")
print()
print("Question 13:")
print()
print("Russian psychologist Ivan Pavlov is most famous for conducting experiments using what animals?")
print()
n8=input("Enter your answer here: ")
print()
if n8=="dog" or n8=="Dog" or n8=="DOG":
    print("Your answer is correct")
    i8=i8+3
else:
    print("Your answer is incorrect.")
    print()
    print("The correct answer is Dog.")
print()
input("Press enter to continue to next question")
print()
print("Question 14:")
print()
print("Sigmund Freud believed that human personality consists of three elements. One is the Id, the other is the Ego. Name the third element?")
print()
o8=input("Enter your answer here: ")
print()
if o8=="Superego" or o8=="superego" or o8=="SUPEREGO":
    print("Your answer is correct")
    i8=i8+3
else:
    print("Your answer is incorrect.")
    print()
    print("The correct answer is Superego.")
print()
input("Press enter to continue to next question")
print()
print("Question 15:")
print()
print("Is anger a usual response when a person is grieving?")
print()
p8=input("Enter your answer here: ")
print()
if p8=="Yes" or p8=="yes" or p8=="YES":
    print("Your answer is correct")
    i8=i8+3
else:
    print("Yor answer is incorrect.")
    print()
    print("The correct answer is Yes.")
print()
print("                          Thank you for attending Mental Health quiz.")
print()
print("                                      Your score is", i8)
print()
print("                                     Have a great day")