print()
print("                                       Welcome to Hell!")
print("           I hope you're ready, coz only top 0.1% Lucifer fans can get full points.")
print("                                   Hope you'll enjoy this quiz ride.")
print()
print("Question 1:")
print()
print("First things first -- in what city does the show take place?")
print()
print("1. London")
print("2. New York")
print("3. Hong Kong")
print("4. Los Angeles")
print()
a6=int(input("Enter the option number: "))
print()
i6=0
if a6==4:
    print("Your journey has started with a correct answer.")
    i6=i6+1
else:
    print("Your answer is wrong.")
    print()
    print("The correct answer was option 4.")
    print()
    print("'Lucifer' appropriately takes place in Los Angeles, or The City of Angels. L.A. is the second-most-populous city in the US (after The Big Apple), and is, therefore, full of sinners for our anti-hero to punish.")
print()
input("Press enter to continue to next question")
print()
print("Question 2:")
print()
print("What is the name of Lucifer’s nightclub?")
print()
print("1. Luci's Place")
print("2. Hell on Earth")
print("3. Lux")
print("4. Eden")
print()
b6=int(input("Enter the option number: "))
print()
if b6==3:
    print("Your answer is correct.")
    i6=i6+1
else:
    print("Your answer is wrong.")
    print()
    print("The correct answer was option 3.")
    print()
    print("Lucifer named his nightclub Lux, the Latin word for light. In Latin, 'lux' is both the prefix and the basis of the word Lucifer, which translates to 'the Lightbringer'.")
print()
input("Press enter to continue to next question")
print()
print("Question 3: ")
print()
print("What musical instrument is Lucifer often seen playing?")
print()
print("1. Guitar")
print("2. Bass")
print("3. Piano")
print("4. He sings acapella.")
print()
c6=int(input("Enter the option number: "))
print()
if c6==3:
    print("Your answer is correct.")
    i6=i6+1
else:
    print("Your answer is wrong.")
    print()
    print("The correct answer was option 3.")
    print()
    print('Lucifer is often shown playing piano and singing at Lux. The singing is really done by Tom Ellis, the actor who plays Lucifer. He does not, however, play the piano.')
print()
input("Press enter to continue to next question")
print()
print("Question 4:")
print()
print("Lucifer has a large scar that reveals part of his angelic nature. What is it?")
print()
print("1. A halo around his head")
print("2. Wings on his back")
print("3. A tail on his butt")
print("4. Horns on his forehead")
print()
d6=int(input("Enter the option here: "))
print()
if d6==2:
    print("Your answer is correct.")
    i6=i6+1
else:
    print("Your answer is wrong.")
    print()
    print("The correct answer was option 2.")
    print()
    print("As much as we would all have loved it to be C so we could have gratuitous shots of Tom Ellis's rear end, we had to make do with shots of his equally gorgeous back. Lucifer is shown to have scars on his back from where Maze cut off his wings (at his command).")
print()
input("Press enter to continue to next question")
print()
print("Question 5:")
print()
print("Lucifer is never far from his demon friend, Maze. What is 'Maze' short for?")
print()
print("1. Mazikeen")
print("2. Mazee")
print("3. Mazoula")
print("4. Maze isn't short for anything.")
print()
e6=int(input("Enter your option here: "))
print()
if e6==1:
    print("Your answer is correct.")
    i6=i6+1
else:
    print("Your answer was incorrect.")
    print()
    print("The correct answer was option 1.")
    print()
    print("Mazikeen is very picky about who is allowed to call her by her nickname, Maze. Maze is played by Lesley-Ann Brandt, who also played Lamia in the TV series The Librarians.")
print()
input("Press enter to continue to next question")
print()
print("Question 6:")
print()
print("How long before the events of the first episode had Lucifer and Maze been in L.A.?")
print()
print("1. One week")
print("2. Six months")
print("3. One year")
print("4. Five years")
print()
f6=int(input("Enter your option here: "))
print()
if f6==4:
    print("Your answer is correct.")
    i6=i6+1
else:
    print("Your answer was incorrect.")
    print()
    print("The correct answer was option 4.")
    print()
    print("In the pilot episode, Chloe says that she did some digging into Lucifer and can't find any records of him going back further than five years. It's later revealed that Lucifer paid an undertaker to forge ID papers for him and Maze.")
print()
input("Press enter to continue to next question")
print()
print("Question 7:")
print()
print("Which human has seen Maze's real face?")
print()
print("1. Chloe")
print("2. Trixie")
print("3. Linda")
print("4. Dan")
print()
g6=int(input("Enter your option here: "))
print()
if g6==2:
    print("Your answer is correct.")
    i6=i6+1
else:
    print("Your answer was incorrect.")
    print()
    print("The correct answer was option 2.")
    print()
    print("While trick-or-treating, Maze shows her true face to her friend Trixie. Trixie thinks it's 'cool' and remarks that they're 'gonna get so much candy'. Maze did let her true face show while stalking Chloe early in season one, but Chloe was asleep and didn't see.")
print()
input("Press enter to continue to next question")
print()
print("Question 8:")
print()
print("Family is important to Chloe, her daughter Trixie being paramount. What is Trixie's real name?")
print()
print("1. Tricia")
print("2. Beatta")
print("3. Beatrice")
print("4. Trixie is her real name.")
print()
h6=int(input("Enter your option here: "))
print()
if h6==3:
    print("Your answer is correct.")
    i6=i6+1
else:
    print("Your answer is wrong.")
    print()
    print("The correct answer was option 3.")
    print()
    print("While only mentioned briefly, Trixie is a nickname. Her real name is Beatrice. Trixie is played by Scarlett Estevez, who recently appeared in the Will Ferrel movie Daddy's Home.")
print()
input("Press enter to continue to next question")
print()
print("Question 9:")
print()
print("In season 2, information about Chloe's conception was revealed. How was she conceived?")
print()
print("1. Naturally but unplanned")
print("2. Naturally and planned")
print("3. Through IVF and other infertility treatments")
print("4. God sent Amenadiel to bless her parents")
print()
j6=int(input("Enter your option here: "))
print()
if j6==4:
    print("Your answer is correct.")
    i6=i6+1
else:
    print("Your answer was incorrect.")
    print()
    print("The correct answer was option 4.")
    print()
    print("Amenadiel is played by D.B. Woodside. Whedon fans will recognize Woodside as Principal Wood on Buffy the Vampire Slayer.")
print()
input("Press enter to continue to next question")
print()
print("Question 10:")
print()
print("Who is Maze's spouse?")
print()
print("1. Dan")
print("2. Ella")
print("3. Linda")
print("4. Eve")
print()
k6=int(input("Enter you option here: "))
print()
if k6==4:
    print("Your answer is correct.")
    i6=i6+1
else:
    print("Your answer was incorrect.")
    print()
    print("The correct answer was option 4.")
    print()
    print("In Season 6 episode 7. Maze marry her love of her life 'Eve' who is the mother of all humans, after leveaing her ex Adam.")
print()
print("Here Completes your MCQ part.")
print()
input("Press enter to continue.")
print()
print("This is your typing part which is worth 3 points.")
print()
input("Press enter to continue to next question")
print()
print("Question 11: ")
print()
print("What is Chloe's mother's name?")
print()
l6=input("Enter your answer here: ")
print()
if l6=="Penelope" or l6=="PENELOPE" or l6=="penelope":
    print("Your answer is correct")
    i6=i6+3
else:
    print("Yor answer is incorrect.")
    print()
    print("The correct answer is Penelope.")
print()
input("Press enter to continue to next question")
print()
print("Question 12:")
print()
print("What does Lucifer call Dan? Detective _______")
print()
m6=input("Enter your answer here: ")
print()
if m6=="Douche" or m6=="douche" or m6=="DOUCHE":
    print("Your answer is correct")
    i6=i6+3
else:
    print("Your answer is incorrect.")
    print()
    print("The correct answer is Douche.")
print()
input("Press enter to continue to next question")
print()
print("Question 13:")
print()
print("When the series began, Chloe is an outsider at LAPD, due to her stance on an officer-involved shooting known as what?")
print()
n6=input("Enter your answer here: ")
print()
if n6=="palmetto" or n6=="Palmetto" or n6=="PALMETTO":
    print("Your answer is correct")
    i6=i6+3
else:
    print("Your answer is incorrect.")
    print()
    print("The correct answer is Palmetto.")
print()
input("Press enter to continue to next question")
print()
print("Question 14:")
print()
print("Maze and Trixie get along so well that Maze ends up taking Trixie trick-or-treating when Chloe has to work. What outfit did Chloe leave for Trixie to wear?")
print()
o6=input("Enter your answer here: ")
print()
if o6=="Princess" or o6=="princess" or o6=="PRINCESS":
    print("Your answer is correct")
    i6=i6+3
else:
    print("Your answer is incorrect.")
    print()
    print("The correct answer is Princess.")
print()
input("Press enter to continue to next question")
print()
print("Question 15:")
print()
print("Uriel brings a special blade with him to wipe their mother out of existence. To whom does this blade belong?")
print()
p6=input("Enter your answer here: ")
print()
if p6=="Azrael" or p6=="AZRAEL" or p6=="azrael":
    print("Your answer is correct")
    i6=i6+3
else:
    print("Yor answer is incorrect.")
    print()
    print("The correct answer is Azrael.")
print()
print("                          Thank you for attending Lucifer quiz.")
print()
print("                                      Your score is", i6)
print()
print("                                     Have a great day")