print()
print("                                     Welcome to Mental Health Quiz!")
print("                             This will test your knowledge on Mental Health")
print("                            Hope you'll enjoy this quiz and learn new things")
print()
print("Question 1:")
print()
print("What are Human Rights?*")
print()
print("1. A way in which the government can monitor people.")
print("2. Concepts which Parliament aspire to as they create laws")
print("3. Basic rights and freedoms accorded to all people")
print("4.  Basic rights and freedoms accorded to all who live in States which have signed up to the ECHR")
print()
a4=int(input("Enter the option number: "))
print()
i4=0
if a4==3:
    print("Your answer is correct.")
    i4=i4+1
else:
    print("Your answer is wrong.")
    print()
    print("The correct answer was option 3.")
print()
input("Press enter to continue to next question")
print()
print("Question 2:")
print()
print("When did the Human Rights Act 1998 come into force?*")
print()
print("1. 15th December 1998")
print("2. 2nd October 2000")
print("3. 1st January 1999")
print("4. 20th October 1998")
print()
b4=int(input("Enter the option number: "))
print()
if b4==2:
    print("Your answer is correct.")
    i4=i4+1
else:
    print("Your answer is wrong.")
    print()
    print("The correct answer was option 2.")
print()
input("Press enter to continue to next question")
print()
print("Question 3: ")
print()
print("Why is Human Rights Day celebrated on 10th December?")
print()
print("1. The day the ECHR was founded")
print("2. The day the UN adopted the Universal Declaration of Human Rights")
print("3. No reason")
print("4. It commemorates the recognition of the Convention against Torture")
print()
c4=int(input("Enter the option number: "))
print()
if c4==2:
    print("Your answer is correct.")
    i4=i4+1
else:
    print("Your answer is wrong.")
    print()
    print("The correct answer was option 2.")
print()
input("Press enter to continue to next question")
print()
print("Question 4:")
print()
print("Which Article gives the right to a fair trial?")
print()
print("1. 11")
print("2. 6")
print("3. 5")
print("4. 7")
print()
d4=int(input("Enter the option here: "))
print()
if d4==2:
    print("Your answer is correct.")
    i4=i4+1
else:
    print("Your answer is wrong.")
    print()
    print("The correct answer was option 2.")
print()
input("Press enter to continue to next question")
print()
print("Question 5:")
print()
print("Which of the following are qualified rights?")
print()
print("1. Right to respect for private and family life, freedom to manifest your religion or belief, freedom of expression, freedom of assembly")
print("2. Right to life, right to liberty and security, right to respect for private and family life")
print("3. Right to marry and start a family, no punishment without law, freedom to manifest your religion or belief")
print("4. Freedom from slavery and forced labour, freedom from torture and inhuman or degrading treatment, right to a fair trial")
print()
e4=int(input("Enter your option here: "))
print()
if e4==1:
    print("Your answer is correct.")
    i4=i4+1
else:
    print("Your answer was incorrect.")
    print()
    print("The correct answer was option 1.")
print()
input("Press enter to continue to next question")
print()
print("Question 6:")
print()
print("What is the importance of Article 15?")
print()
print("1. It gives a Member State derogation powers")
print("2. It is the Article against torture")
print("3. It contains the signatures of the Member States")
print("4. It explains the difference between absolute and qualified rights")
print()
f4=int(input("Enter your option here: "))
print()
if f4==1:
    print("Your answer is correct.")
    i4=i4+1
else:
    print("Your answer was incorrect.")
    print()
    print("The correct answer was option 1.")
print()
input("Press enter to continue to next question")
print()
print("Question 7:")
print()
print("What is the most common cause for a Member State to use a derogation order?")
print()
print("1. Internal conflicts and terrorist threats")
print("2. When at war with another Member State")
print("3. When a case reaches their national Supreme Court level")
print("4. Terrorist threats")
print()
g4=int(input("Enter your option here: "))
print()
if g4==1:
    print("Your answer is correct.")
    i4=i4+1
else:
    print("Your answer was incorrect.")
    print()
    print("The correct answer was option 1.")
print()
input("Press enter to continue to next question")
print()
print("Question 8:")
print()
print("The seminal Nicklinson case revealed tensions between the Suicide Act 1961 and which Convention right?")
print()
print("1. Right to a fair trial")
print("2. Right to life")
print("3. Right to private and family life")
print("4. Freedom of expression")
print()
h4=int(input("Enter your option here: "))
print()
if h4==3:
    print("Your answer is correct.")
    i4=i4+1
else:
    print("Your answer is wrong.")
    print()
    print("The correct answer was option 3.")
print()
input("Press enter to continue to next question")
print()
print("Question 9:")
print()
print("What did Daly establish?")
print()
print("1. Prisoners have a right to private correspondence with lawyers")
print("2. Prisoners can vote in general elections")
print("3. Prisoners who risk persecution due to their sexuality can ask to move prisons")
print("4. Prisoners can request that their life sentences are reviewed")
print()
j4=int(input("Enter your option here: "))
print()
if j4==1:
    print("Your answer is correct.")
    i4=i4+1
else:
    print("Your answer was incorrect.")
    print()
    print("The correct answer was option 1.")
print()
input("Press enter to continue to next question")
print()
print("Question 10:")
print()
print("Which core Human Rights treaty has been signed by the most countries?")
print()
print("1. The Convention on the Rights of the Child")
print("2. The Convention on the Elimination of All Forms of Racial Discrimination")
print("3. The UN Convention Against Torture")
print("4. The Convention on the Elimination of All Forms of Discrimination")
print()
k4=int(input("Enter you option here: "))
print()
if k4==1:
    print("Your answer is correct.")
    i4=i4+1
else:
    print("Your answer was incorrect.")
    print()
    print("The correct answer was option 1.")
print()
print("Here Completes your MCQ part.")
print()
input("Press enter to continue.")
print()
print("This is your typing part which is worth 3 points.")
print()
input("Press enter to continue to next question")
print()
print("Question 11: ")
print()
print("The General Assembly of UNO has adopted Declaration on Rights of Disabled Persons in year ___")
print()
l4=input("Enter your answer here: ")
print()
if l4=="1995":
    print("Your answer is correct")
    i4=i4+3
else:
    print("Yor answer is incorrect.")
    print()
    print("The correct answer is 1995.")
print()
input("Press enter to continue to next question")
print()
print("Question 12:")
print()
print(" In which century human rights became a central concern over the issue of slavery?")
print()
m4=input("Enter your answer here: ")
print()
if m4=="19th" or m4=="19":
    print("Your answer is correct")
    i4=i4+3
else:
    print("Your answer is incorrect.")
    print()
    print("The correct answer is 19th.")
print()
input("Press enter to continue to next question")
print()
print("Question 13:")
print()
print("Where is the headquarter of the National Human Rights Commission in India?")
print()
n4=input("Enter your answer here: ")
print()
if n4=="delhi" or n4=="Delhi" or n4=="DELHI":
    print("Your answer is correct")
    i4=i4+3
else:
    print("Your answer is incorrect.")
    print()
    print("The correct answer is Delhi.")
print()
input("Press enter to continue to next question")
print()
print("Question 14:")
print()
print("How many articles are there in the Universal Declaration of Human Rights?")
print()
o4=input("Enter your answer here: ")
print()
if o4=="30":
    print("Your answer is correct")
    i4=i4+3
else:
    print("Your answer is incorrect.")
    print()
    print("The correct answer is 30.")
print()
input("Press enter to continue to next question")
print()
print("Question 15:")
print()
print("Under whose chairmanship The United Declaration of Human Rights was adopted?")
print()
p4=input("Enter your answer here: ")
print()
if p4=="Eleanor Roosevelt" or p4=="eleanor roosevelt" or p4=="ELEANOR ROOSEVELT":
    print("Your answer is correct")
    i4=i4+3
else:
    print("Yor answer is incorrect.")
    print()
    print("The correct answer is Eleanor Roosevelt.")
print()
print("                          Thank you for attending Human Rights quiz.")
print()
print("                                      Your score is", i4)
print()
print("                                     Have a great day")