s=0
s2=0
print()
print("                                                         Welcome to the Music section!")
print()
print("Question 1")
print()
print("Name the person who replaced Ozzy Osbourne as Black Sabbath ‘s lead singer?")
print("1. Ronnie James Dio")
print("2. Judas Priest")
print("3. Dokken")
print("4. Whitesnake")
a1=int(input("Enter the option number: "))
print()
if a1==1:
    print("Your answer is Correct!")
    print("Ronnie James Dio replaced original vocalist Ozzy Osbourne in 1979, and initially recorded two studio albums.")
    s=s+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 1!")
    print("Ronnie James Dio replaced original vocalist Ozzy Osbourne in 1979, and initially recorded two studio albums.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 2")
print()
print("To consider a band as a Big Band what is the minimum number of musicians to be needed?")
print("1. 11")
print("2. 21")
print("3. 12")
print("4. 10")
a1=int(input("Enter the option number: "))
print()
if a1==4:
    print("Your answer is Correct!")
    print("A big band or jazz orchestra is a type of musical ensemble of jazz music that usually consists of ten or more musicians with four sections: saxophones, trumpets, trombones, and a rhythm section.")
    s=s+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 4!")
    print("A big band or jazz orchestra is a type of musical ensemble of jazz music that usually consists of ten or more musicians with four sections: saxophones, trumpets, trombones, and a rhythm section.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 3")
print()
print(" In an Orchestra, which is the largest brass section instrument?")
print("1. Trumpet")
print("2. Tenor")
print("3. French horns")
print("4. Tuba")
a1=int(input("Enter the option number: "))
print() 
if a1==4:
    print("Your answer is Correct! ")
    print("The tuba is the largest and lowest brass instrument and anchors the harmony not only of the brass family but the whole orchestra with its deep rich sound.")
    s=s+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 4!")
    print("The tuba is the largest and lowest brass instrument and anchors the harmony not only of the brass family but the whole orchestra with its deep rich sound.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 4")
print()
print("Name the singer who released the album, Here, My Dear?")
print("1. Frankie Gaye")
print("2. Bruno Mars")
print("3. Elton John")
print("4. Marvin Gaye")
a1=int(input("Enter the option number: "))
print()
if a1==4:
    print("Your answer is Correct!")
    print("Here, My Dear is the fifteenth studio album by music artist Marvin Gaye, released as a double album on December 15, 1978, on Motown-subsidiary label Tamla Records.")
    s=s+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 4!")
    print("Here, My Dear is the fifteenth studio album by music artist Marvin Gaye, released as a double album on December 15, 1978, on Motown-subsidiary label Tamla Records.")
print()
input("Press enter  any key to continue to the next question")
print()
print()
print("Question 5")
print()
print("Name the orchestral instrument that can play high note?")
print("1. Viola")
print("2. Piccolo")
print("3. Violin")
print("4. Cellos")
a1=int(input("Enter the option number: "))
print()
if a1==3:
    print("Your answer is Correct!")
    print("The violin is the smallest and highest-pitched member of the string family.")
    s=s+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 3!")
    print("The violin is the smallest and highest-pitched member of the string family.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 6")
print()
print("It is said that Tabla was invented accidentally during a stage performance by an artist. Name the instrument from which Tabla was believed to be invented.")
print("1. Bongo")
print("2. Mridangam")
print("3. Dholak")
print("4. Guitar")
a1=int(input("Enter the option number: "))
print()
if a1==2:
    print("Your answer is Correct!")
    print("The mridangam is a percussion instrument of ancient origin. It is the primary rhythmic accompaniment in a Carnatic music ensemble.")
    s=s+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 2!")
    print("The mridangam is a percussion instrument of ancient origin. It is the primary rhythmic accompaniment in a Carnatic music ensemble.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 7")
print()
print(" How many sounds does Tabla produce?")
print("1. 3")
print("2. 4")
print("3. 12")
print("4. 18")
a1=int(input("Enter the option number: "))
print()
if a1==3:
    print("Your answer is Correct!")
    print("A Tabla produces 12 sounds.")
    s=s+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 3!")
    print("A Tabla produces 12 sounds.") 
print()
input("Press enter  any key to continue to the next question")
print()
print()
print("Question 8")
print()
print("An excessive fondness for music is called :")
print("1. Megalomania")
print("2. Hypomania")
print("3. Graphomania")
print("4. Melomania")
a1=int(input("Enter the option number: "))
print()
if a1==4:
    print("Your answer is Correct!")
    print("The meaning of MELOMANIA is an inordinate liking for music or melody : excessive or abnormal attraction to music.") 
    s=s+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 4!")
    print("The meaning of MELOMANIA is an inordinate liking for music or melody : excessive or abnormal attraction to music.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 9")
print()
print("Which one of these Tabla players has received Padma Vibhushan, the second highest civilian award given by the government of India?")
print("1. Zakir Hussain")
print("2. Ustaad Allahrakha")
print("3. Pt. Kishan Maharaj")
print("4. Ustad Abdul Latif")
a1=int(input("Enter the option number: "))
print()
if a1==1:
    print("Your answer is Correct!")
    print("Ustad Zakir Hussain (born 9 March 1951) is an Indian tabla virtuoso, composer, percussionist, music producer and film actor. ") 
    s=s+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 1!")
    print("Ustad Zakir Hussain (born 9 March 1951) is an Indian tabla virtuoso, composer, percussionist, music producer and film actor. ")
print()
input("Press enter  any key to continue to the next question")
print()
print()
print("Question 10")
print()
print("What material is the Indian flute made of?")
print("1. Steel")
print("2. Plastic")
print("3. Wood")
print("4. Glass")
a1=int(input("Enter the option number: "))
print()
if a1==3:
    print("Your answer is Correct!")
    print("The Indian flutes are very simple compared to the Western counterparts; they are made of bamboo and are keyless.") 
    s=s+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 3!")
    print("The Indian flutes are very simple compared to the Western counterparts; they are made of bamboo and are keyless.")
print()
print()
print("Your score in the MCQ segment is",s,"out of 10 ! ")
print()
input("Press enter to proceed to the Fill in the blanks segment.")
print()
print("Question 1")
print()
print("Which 80s star is recognised by Guinness World Records as the best-selling female recording artist of all time?")
a2=input("Enter your answer: ")
if a2=="Madonna"or a2=="Madona" or a2=="madonna":
     print("Your answer is correct!")
     s2=s2+1
else:
      print("Your answer is incorrect!")
      print("The correct answer is Madonna.")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 2")
print()
print("When was Lata Mangeshkar awarded the Padma Bhushan?")
a2=int(input("Enter your answer: "))
print()
if a2==1969:
     print("Your answer is correct!")
     s2=s2+1
else:
      print("Your answer is incorrect!")
      print("The correct answer is 1969.")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 3")
print()
print("The Beatles consisted of four members: John, Paul, Ringo, and who?")
a2=input("Enter your answer: ")
print()
if a2=="George" or a2=="george":
     print("Your answer is correct!")
     s2=s2+1
else:
      print("Your answer is incorrect!")
      print("The correct answer is George.")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 4")
print()
print("In which country was singer Rihanna born?")
a2=input("Enter your answer: ")
print()
if a2=="Barbados" or a2=="barbados":
     print("Your answer is correct!")
     s2=s2+1
else:
      print("Your answer is incorrect!")
      print("The correct answer is Barbados.")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 5")
print()
print("Who is the singer of the song Believer ?")
a2=input("Enter your answer: ")
print()
if a2=="Imagine Dragons"or a2=="imagine dragons":
     print("Your answer is correct!")
     s2=s2+1 
else:
      print("Your answer is incorrect!")
      print("The correct answer is Imagine Dragons.")
print()
print()
print("Your score in the Fill in the blanks segment is",s2,"out of 15!")
print()
print("Your total score is",s+s2,"out of 25!")
print()
print("The trivia is over!")
print("Thank You")



          

