i5a=0
i5b=0
print()
print("                                                         Welcome to the Politics section!")
print()
print("Question 1")
print()
print("Who proposed the Preamble before the Drafting Committee of the Constitution?")
print("1. Jawaharlal Nehru")
print("2. B.R. Ambedkar")
print("3. B.N.Rau")
print("4. Mahatma Gandhi")
a5a=int(input("Enter the option number: "))
print()
if a5a==1:
    print("Your answer is Correct!")
    print("Jawaharlal Nehru proposed the creation of the Preamble before the drafting committee of the Constitution and then it was adopted by the Constituent Assembly.")
    i5a=i5a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 1!")
    print("Jawaharlal Nehru proposed the creation of the Preamble before the drafting committee of the Constitution and then it was adopted by the Constituent Assembly.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 2")
print()
print("In which year, Constitution of India was amended for the first time?")
print("1. 1950")
print("2. 1951")
print("3. 1952")
print("4. 1953")
a5a=int(input("Enter the option number: "))
print()
if a5a==2:
    print("Your answer is Correct!")
    print("The Constitution (First Amendment) Act, 1951, enacted in 1951, had made several changes to the provisions related to Fundamental Rights s to check abuse of freedom of speech and expression; validation of zamindari abolition laws etc. This amendment provided that right to equality does not bar the enactment of laws which provide “special consideration” for weaker sections of society.")
    i5a=i5a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 2!")
    print("The Constitution (First Amendment) Act, 1951, enacted in 1951, had made several changes to the provisions related to Fundamental Rights s to check abuse of freedom of speech and expression; validation of zamindari abolition laws etc. This amendment provided that right to equality does not bar the enactment of laws which provide “special consideration” for weaker sections of society.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 3")
print()
print(" Who among the following has been given rights to legislate on residuary subjects?")
print("1. State government")
print("2. Central government")
print("3. Both central and state governments")
print("4. President")
a5a=int(input("Enter the option number: "))
print()
if a5a==2:
    print("Your answer is Correct!")
    print("Matters which are not included in any of the three lists (Union, State, Concurrent) are known as residuary subjects.")
    i5a=i5a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 2!")
    print("Matters which are not included in any of the three lists (Union, State, Concurrent) are known as residuary subjects")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 4")
print()
print("Who called Indian people as “a single people living under a single imperium derived from a single source”?")
print("1. Jawaharlal Nehru")
print("2. Vallabhbhai Patel")
print("3. Dr. B R Ambedkar")
print("4. Mahatma Gandhi")
a5a=int(input("Enter the option number: "))
print()
if a5a==3:
    print("Your answer is Correct!")
    print("Though the country and the people may be divided into different States for convenience of administration, the country is one integrated whole, its people a single people, living under a single imperium derived from a single source. - Dr. B. R. Ambedkar")
    i5a=i5a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 3!")
    print("Though the country and the people may be divided into different States for convenience of administration, the country is one integrated whole, its people a single people, living under a single imperium derived from a single source. - Dr. B. R. Ambedkar")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 5")
print()
print("Which among the following articles of Constitution of India deals with “Prohibition of Traffic in Human beings” ?")
print("1. Article 21")
print("2. Article 22")
print("3. Article 23")
print("4. Article 24")
a5a=int(input("Enter the option number: "))
print()
if a5a==3:
    print("Your answer is Correct!")
    print("Article 23 provides for prohibition of traffic in human beings and forced labour.")
    i5a=i5a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 3!")
    print("Article 23 provides for prohibition of traffic in human beings and forced labour.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 6")
print()
print("Who is the current Chief Minister of Maharashtra? ")
print("1. Devendra Fadnavis")
print("2. Sharad Pawar")
print("3. Udhav Thackeray")
print("4. Yogi Adityanath")
a5a=int(input("Enter the option number: "))
print()
if a5a==3:
    print("Your answer is Correct!")
    print("Uddhav Balasaheb Thackeray is an Indian politician who is the 19th and current Chief Minister of Maharashtra. He is also the president of Shiv Sena.")
    i5a=i5a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 3!")
    print("Uddhav Balasaheb Thackeray is an Indian politician who is the 19th and current Chief Minister of Maharashtra. He is also the president of Shiv Sena.")
print()
input("Press enter any to continue to the next question")
print()
print()
print("Question 7")
print()
print(" Who is the Defence Minister of India?")
print("1. Amit Shah")
print("2. Rajnath Singh")
print("3. Nirmala Sitharaman")
print("4. Nitin Gadkari")
a5a=int(input("Enter the option number: "))
print()
if a5a==2:
    print("Your answer is Correct!")
    print("Rajnath Singh is an Indian politician serving as the Defence Minister of India. He is currently the Deputy Leader of the House Lok Sabha. He is the former President of BJP.")
    i5a=i5a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 2!")
    print("Rajnath Singh is an Indian politician serving as the Defence Minister of India. He is currently the Deputy Leader of the House Lok Sabha. He is the former President of BJP.") 
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 8")
print()
print("Which state assembly has the maximum number of members?")
print("1. Uttar Pradesh")
print("2. Maharashtra")
print("3. West Bengal")
print("4. Andhra Pradesh")
a5a=int(input("Enter the option number: "))
print()
if a5a==1:
    print("Your answer is Correct!")
    print("Uttar Pradesh has highest number of state legislative assembly seats, which are 403 in number.") 
    i5a=i5a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 1!")
    print("Uttar Pradesh has highest number of state legislative assembly seats, which are 403 in number.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 9")
print()
print("The term 'Gram Sabha' denotes-")
print("1. Senior citizens of a village")
print("2. Population of a village")
print("3. Electoral college for Panchayat")
print("4. Elected members of Panchayat")
a5a=int(input("Enter the option number: "))
print()
if a5a==3:
    print("Your answer is Correct!")
    print("73rd Amendment of constitution also provides for Gram Sabha at village level as foundation stone of the whole system of governance. It is a village assembly consisting of all registered voters in the area of Panchayat which constitute electoral college for Panchayat. ") 
    i5a=i5a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 3!")
    print("73rd Amendment of constitution also provides for Gram Sabha at village level as foundation stone of the whole system of governance. It is a village assembly consisting of all registered voters in the area of Panchayat which constitute electoral college for Panchayat")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 10")
print()
print("Who is the Chief Minister of Goa?")
print("1. Pramod Sawant")
print("2. Arvind Kejriwal")
print("3. Manohar Parrikar")
print("4. Naveen Patnaik")
a5a=int(input("Enter the option number: "))
print()
if a5a==1:
    print("Your answer is Correct!")
    print("Pramod Sawant is an Indian politician who is the 13th and current Chief Minister of Goa. He is an Ayurveda Medical practitioner by profession. ") 
    i5a=i5a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 1!")
    print("Pramod Sawant is an Indian politician who is the 13th and current Chief Minister of Goa. He is an Ayurveda Medical practitioner by profession.")
print()
print("Your score in the MCQ segment is",i5a,"out of 10!")
print()
input("Press enter to proceed to the Fill in the blanks segment.")
print()
print()
print("Question 1")
print()
print("Who is the head of Indian Constitution?")
a5b=input("Enter your answer: ")
if a5b=="President"or a5b=="president":
     print("Your answer is correct!")
     i5b=i5b+1
else:
     print("Your answer is incorrect!")
     print("The correct answer is President.")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 2")
print()
print("Ashok Gehlot is the Chief Minister of which Indian state?")
a5b=input("Enter your answer: ")
print()
if a5b=="Rajasthan" or a5b=="rajasthan":
     print("Your answer is correct!")
     i5b=i5b+1
else:
     print("Your answer is incorrect!")
     print("The correct answer is Rajasthan.")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 3")
print()
print("Which is the largest union territory in India?")
a5b=input("Enter your answer: ")
print()
if a5b=="Pondicherry"or a5b=="pondicherry":
     print("Your answer is correct!")
     i5b=i5b+1
else:
     print("Your answer is incorrect!")
     print("The correct answer is Pondicherry.")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 4")
print()
print("Who started the Quit India movement in the year 1942? ")
a5b=input("Enter your answer: ")
print()
if a5b=="Mahatma Gandhi"or a5b=="Gandhi"or a5b=="gandhi":
     print("Your answer is correct!")
     i5b=i5b+1
else:
     print("Your answer is incorrect!")
     print("The correct answer is Mahatma Gandhi.")
      
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 5")
print()
print("Who hosts the flag on Independence Day at Delhi Fort?")
a5b=input("Enter your answer: ")
print()
if a5b=="Prime Minister"or a5b=="PM"or a5b=="prime minister":
     print("Your answer is correct!")
     i5b=i5b+1
else:
     print("Your answer is incorrect!")
     print("The correct answer is Prime Minister.")
print()
print("Your score in the Fill in the blank segment is",i5b,"out of 15")
print()
print("Your total score is",i5a+i5b,"out of 25!")
print()
print("The trivia is over!")
print("Thank You")



