i9a=0
i9b=0
print()
print("                                                         Welcome to the Sports section!")
print()
print("Question 1")
print()
print("After how many Year’s FIFA World Cup is held?")
print("1. 2 Years")
print("2. 3 Years")
print("3. 4 Years")
print("4. Every Year")
a9a=int(input("Enter the option number: "))
print()
if a9a==3:
    print("Your answer is Correct!")
    print("The World Cup happens every four years in order to have enough time for the qualification tournaments and playoffs among national teams to take place.")
    i9a=i9a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 3!")
    print("The World Cup happens every four years in order to have enough time for the qualification tournaments and playoffs among national teams to take place.")
print()
input("Press enter to continue to the next question")
print()
print()
print("Question 2")
print()
print("Who is known as the Flying Sikh?")
print("1. Michael Johnson")
print("2. Usain Bolt")
print("3. Milkha Singh")
print("4. Carl Lewis")
a9a=int(input("Enter the option number: "))
print()
if a9a==3:
    print("Your answer is Correct!")
    print("Known as the Flying Sikh by his admirers, Milkha Singh was an Indian track and field sprinter and is the only athlete to win a gold medal in the 400 metres race at the Asian Games as well as the Commonwealth Games.")
    i9a=i9a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 3!")
    print("Known as the Flying Sikh by his admirers, Milkha Singh was an Indian track and field sprinter and is the only athlete to win a gold medal in the 400 metres race at the Asian Games as well as the Commonwealth Games.")
print()
input("Press enter to continue to the next question")
print()
print()
print("Question 3")
print()
print("Who has the Highest Number of Gold Medals in Olympic History?")
print("1. Larisa Latynina")
print("2. Mark Spitz")
print("3. Saina Nehwal")
print("4. Michael Phelps")
a9a=int(input("Enter the option number: "))
print()
if a9a==4:
    print("Your answer is Correct!")
    print("Michael Phelps has won 23 Gold medals.")
    i9a=i9a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 4!")
    print("Michael Phelps has won 23 Gold medals.")
print()
input("Press enter to continue to the next question")
print()
print()
print("Question 4")
print()
print("What is the National Sports of China?")
print("1. Table Tennis")
print("2. Baseball")
print("3. Cricket")
print("4. Swimming")
a9a=int(input("Enter the option number: "))
print()
if a9a==1:
    print("Your answer is Correct!")
    print("Table tennis is the national sport of China.")
    i9a=i9a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 1!")
    print("Table tennis is the national sport of China.")
print()
input("Press enter to continue to the next question")
print()
print()
print("Question 5")
print()
print("Who is given the Nickname “God of Cricket”?")
print("1. Ricky Ponting")
print("2. Virat Kohli")
print("3. MS Dhoni")
print("4. Sachin Tendulkar")
a9a=int(input("Enter the option number: "))
print()
if a9a==4:
    print("Your answer is Correct!")
    print("As said by his fans, Sachin Tendulkar is the God of cricket. He's called so because of the records he made that are considered to be unbreakable over years.")
    i9a=i9a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 4!")
    print("As said by his fans, Sachin Tendulkar is the God of cricket. He's called so because of the records he made that are considered to be unbreakable over years.")
print()
input("Press enter to continue to the next question")
print()
print()
print("Question 6")
print()
print("Which Team did Kobe Bryant play for?")
print("1. Chicago Bulls")
print("2. Golden State Warriors")
print("3. Los Angeles Lakers")
print("4. Miami Heat")
a9a=int(input("Enter the option number: "))
print()
if a9a==3:
    print("Your answer is Correct!")
    print("Kobe Bryant, an American professional basketball player ,helped lead the Los Angeles Lakers of the National Basketball Association (NBA) to five championships (2000–02 and 2009–10)")
    i9a=i9a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 3!")
    print("Kobe Bryant, an American professional basketball player ,helped lead the Los Angeles Lakers of the National Basketball Association (NBA) to five championships (2000–02 and 2009–10)")
print()
input("Press enter to continue to the next question")
print()
print()
print("Question 7")
print()
print("What is the Full Form of the NBA?")
print("1. National Premier Basketball Association")
print("2. North Basketball Association")
print("3. National Bundesliga Association")
print("4. National Basketball Association")
a9a=int(input("Enter the option number: "))
print()
if a9a==4:
    print("Your answer is Correct!")
    print("The National Basketball Association or NBA, is a professional basketball league comprised of 30 teams across North America featuring the best basketball players in the world.")
    i9a=i9a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 4!")
    print("The National Basketball Association or NBA, is a professional basketball league comprised of 30 teams across North America featuring the best basketball players in the world.") 
print()
input("Press enter to continue to the next question")
print()
print()
print("Question 8")
print()
print("Which IPL team has won the most number of times?")
print("1. Chennai Super Kings")
print("2. Mumbai Indians")
print("3. Royal Challengers Bangalore")
print("4. Sunrisers Hyderabad")
a9a=int(input("Enter the option number: "))
print()
if a9a==2:
    print("Your answer is Correct!")
    print("Mumbai Indians is the most successful team in IPL history, having won five times while the Chennai Super Kings won the trophy three times.") 
    i9a=i9a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 2!")
    print("Mumbai Indians is the most successful team in IPL history, having won five times while the Chennai Super Kings won the trophy three times.")
print()
input("Press enter to continue to the next question")
print()
print()
print("Question 9")
print()
print("What is Magnus Carlsen famous for?")
print("1. Ludo")
print("2. Chess")
print("3. Poker")
print("4. Billiards")
a9a=int(input("Enter the option number: "))
print()
if a9a==2:
    print("Your answer is Correct!")
    print("Sven Magnus Carlsen is a Norwegian chess grandmaster who is the reigning five-time World Chess Champion. Carlsen is also a three-time World Rapid Chess Champion and five-time World Blitz Chess Champion.") 
    i9a=i9a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 2!")
    print("Sven Magnus Carlsen is a Norwegian chess grandmaster who is the reigning five-time World Chess Champion. Carlsen is also a three-time World Rapid Chess Champion and five-time World Blitz Chess Champion.")
print()
input("Press enter to continue to the next question")
print()
print()
print("Question 10")
print()
print("Which is the Largest Football Stadium in the World?")
print("1. Salt Lake Stadium")
print("2. Rungrado 1st of May Stadium")
print("3. AT&T Stadium")
print("4. Melbourne Cricket Ground")
a9a=int(input("Enter the option number: "))
print()
if a9a==2:
    print("Your answer is Correct!")
    print("The Rungrado 1st of May Stadium is a multi-purpose stadium occupying an area of 20.7 hectares on Rungra Island, Pyongyang, North Korea.") 
    i9a=i9a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 2!")
    print("The Rungrado 1st of May Stadium is a multi-purpose stadium occupying an area of 20.7 hectares on Rungra Island, Pyongyang, North Korea.")
print()
print("Your score in the MCQ segment is",i9a,"out of 10!")
print()
input("Press enter to proceed to the Fill in the blanks segment.")
print()
print("Question 1")
print()
print("The term Grand Slam is associated with which sport?")
a9b=input("Enter your answer: ")
if a9b=="Lawn Tennis"or a9b=="Tennis":
     print("Your answer is correct!")
     i9b=i9b+1
else:
      print("Your answer is incorrect!")
      print("The correct answer is Lawn Tennis.")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 2")
print()
print("In Volley ball, the number of players on each side is?")
a9b=int(input("Enter your answer: "))
if a9b==6:
     print("Your answer is correct!")
     i9b=i9b+1
else:
      print("Your answer is incorrect!")
      print("The correct answer is 6.")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 3")
print()
print("The game of Cricket originated in which country?")
a9b=input("Enter your answer: ")
if a9b=="Britain" or a9b=="britain" or a9b=="UK":
     print("Your answer is correct!")
     i9b=i9b+1
else:
      print("Your answer is incorrect!")
      print("The correct answer is Britain.")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 4")
print()
print("The term Googly is associated with which sports?")
a9b=input("Enter your answer: ")
if a9b=="Cricket"or a9b=="cricket":
     print("Your answer is correct!")
     i9b=i9b+1
else:
      print("Your answer is incorrect!")
      print("The correct answer is Cricket.")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 4")
print()
print("The 'Dronacharya Award' is given to?")
a9b=input("Enter your answer: ")
if a9b=="coaches"or a9b=="Coaches":
     print("Your answer is correct!")
     i9b=i9b+1
else:
      print("Your answer is incorrect!")
      print("The correct answer is Coaches.")
print()
print("Your score in the Fill in the blanks segment is",i9b,"out of 15!")
print()
print("Your total score is",i9a+i9b,"out of 25!")
print()
print("The trivia is over!")
print("Thank You")





    
