i13a=0
i13b=0
print()
print("                                                         Welcome to the Video Games section!")
print()
print("Question 1")
print()
print("What is the name of the orange ghost in Pac-man?")
print("1. Sylve")
print("2. Clyde")
print("3. Tylde")
print("4. Jylde")
a11a=int(input("Enter the option number: "))
print()
if a11a==2:
    print("Your answer is Correct!")
    print("Each of the four ghosts in the game Pacman has both Japanese and English names. In Japan they started as Fickle, Chaser, Ambusher and Stupid. Their English names are Inky, Blinky, Pinky and Clyde.")
    i13a=i13a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 2!")
    print("Each of the four ghosts in the game Pacman has both Japanese and English names. In Japan they started as Fickle, Chaser, Ambusher and Stupid. Their English names are Inky, Blinky, Pinky and Clyde.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 2")
print()
print("What is the main colour of Sonic Hedgehog?")
print("1. Red")
print("2. Green")
print("3. Blue")
print("4. Yellow")
a11a=int(input("Enter the option number: "))
print()
if a11a==3:
    print("Your answer is Correct!")
    print("Sonic is a blue anthropomorphic hedgehog who can run at supersonic speeds and curl into a ball, primarily to attack enemies.")
    i13a=i13a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 3!")
    print("Sonic is a blue anthropomorphic hedgehog who can run at supersonic speeds and curl into a ball, primarily to attack enemies.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 3")
print()
print(" What is the best selling video game console of all time?")
print("1. PlayStation 2")
print("2. Nintendo DS")
print("3. Game Boy")
print("4. XBOX")
a11a=int(input("Enter the option number: "))
print()
if a11a==2:
    print("Your answer is Correct!")
    print("Sony's PlayStation 2 is the best-selling game system overall with over 155 million units worldwide.")
    i13a=i13a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 2!")
    print("Sony's PlayStation 2 is the best-selling game system overall with over 155 million units worldwide.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 4")
print()
print("What is the original name of Sonic the Hedgehog?")
print("1. Speedy the Hedgehog")
print("2. Mr Needlemouse")
print("3. Fast Blue Hedgehog")
print("4. Blue Monster")
a11a=int(input("Enter the option number: "))
print()
if a11a==2:
    print("Your answer is Correct!")
    print("When Sonic the Hedgehog was first in development, he was actually called Mr Needlemouse.")
    i13a=i13a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 2!")
    print("When Sonic the Hedgehog was first in development, he was actually called Mr Needlemouse.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 5")
print()
print("What does Mario work for a living?")
print("1. A Butcher")
print("2. A Painter")
print("3. A Plumber")
print("4. An Electrician")
a11a=int(input("Enter the option number: "))
print()
if a11a==3:
    print("Your answer is Correct!")
    print("Mario's occupation is plumbing, though in the original Donkey Kong games he is a carpenter.")
    i13a=i13a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 3!")
    print("Mario's occupation is plumbing, though in the original Donkey Kong games he is a carpenter.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 6")
print()
print("In Assasin's Creed, which time travelling device is featured? ")
print("1. Epoch")
print("2. Animus")
print("3. Time Sphere")
print("4. Ouija Board")
a11a=int(input("Enter the option number: "))
print()
if a11a==2:
    print("Your answer is Correct!")
    print("The Animus is a machine that allows somebody to revisit the lives of their ancestor's.")
    i13a=i13a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 3!")
    print("The Animus is a machine that allows somebody to revisit the lives of their ancestor's.")
print()
input("Press enter any to continue to the next question")
print()
print()
print("Question 7")
print()
print(" What is the maximum Number players in Among Us?")
print("1. 6")
print("2. 8")
print("3. 10")
print("4. 14")
a11a=int(input("Enter the option number: "))
print()
if a11a==3:
    print("Your answer is Correct!")
    print("A game of Among Us can either be played with just a few or many players. The minimum required number of players to start a game is 4, while the maximum is 10.")
    i13a=i13a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 3!")
    print("A game of Among Us can either be played with just a few or many players. The minimum required number of players to start a game is 4, while the maximum is 10.") 
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 8")
print()
print("Who is Mario's little brother?")
print("1. Wario")
print("2. Luigi")
print("3. Jack")
print("4. Michael")
a11a=int(input("Enter the option number: "))
print()
if a11a==2:
    print("Your answer is Correct!")
    print("Luigi is portrayed as the younger fraternal twin brother and sidekick of Mario, Nintendo's mascot. Luigi appears in many games throughout the Mario franchise, oftentimes accompanying his brother.") 
    i13a=i13a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 2!")
    print("Luigi is portrayed as the younger fraternal twin brother and sidekick of Mario, Nintendo's mascot. Luigi appears in many games throughout the Mario franchise, oftentimes accompanying his brother.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 9")
print()
print("What is the name of the armoured vehicle featured in Halo?")
print("1. Warthog")
print("2. Rocksteady")
print("3. Sir Killalot")
print("4. Gaadi")
a11a=int(input("Enter the option number: "))
print()
if a11a==1:
    print("Your answer is Correct!")
    print("The M12 Force Application Light Reconnaissance Vehicle, nicknamed Warthog, is a fictional armoured fighting vehicle that appears in the Halo video game franchise. An anti-infantry military light utility vehicle with a rear-mounted weapon turret, it appears in most major Halo titles as a drivable vehicle. ") 
    i13a=i13a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 1!")
    print("The M12 Force Application Light Reconnaissance Vehicle, nicknamed Warthog, is a fictional armoured fighting vehicle that appears in the Halo video game franchise. An anti-infantry military light utility vehicle with a rear-mounted weapon turret, it appears in most major Halo titles as a drivable vehicle.")
print()
input("Press enter any key to continue to the next question")
print()
print()
print("Question 10")
print()
print("Which was the first version of Grand Theft Auto to have playable female characters?")
print("1. Grand Theft Auto 1")
print("2. Grand Theft Auto Online")
print("3. Grand Theft Auto: San Andreas")
print("4. Grand Theft Auto 5")
a11a=int(input("Enter the option number: "))
print()
if a11a==1:
    print("Your answer is Correct!")
    print("Grand Theft Auto 1 had the option of four women that the player could choose to play as, though this didn't change the gameplay or story whatsoever and was more for flavor than anything. These first-ever female protagonists in the Grand Theft Auto universe were known as Ulrika, Mikki, Divine, and Katie. ") 
    i13a=i13a+1
else:
    print("Your answer is incorrect!")
    print()
    print("The correct answer was option 1!")
    print("Grand Theft Auto 1 had the option of four women that the player could choose to play as, though this didn't change the gameplay or story whatsoever and was more for flavor than anything. These first-ever female protagonists in the Grand Theft Auto universe were known as Ulrika, Mikki, Divine, and Katie.")
print()
print("Your score in the MCQ segment is",i13a,"out of 10!")
print()
input("Press enter to proceed to the Fill in the blanks segment.")
print()
print("Question 1")
print()
print(" Mario originated as a character in which video game?")
a11b=input("Enter your answer: ")
print()
if a11b=="Donkey Kong"or a11b=="donkey kong":
     print("Your answer is correct!")
     i13b=i13b+1
else:
     print("Your answer is incorrect!")
     print("The correct answer is Donkey Kong.")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 2")
print()
print(" Which famous video game franchise is the game 'V-Bucks' from?")
a11b=input("Enter your answer: ")
print()
if a11b=="Fortnite" or a11b=="fortnite" :
     print("Your answer is correct!")
     i13b=i13b+1
else:
     print("Your answer is incorrect!")
     print("The correct answer is Fortnite.")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 3")
print()
print("Nintendo began as a company that sold which products?")
a11b=input("Enter your answer: ")
print()
if a11b=="Playing Cards"or a11b=="playing cards" or a11b=="Playing cards":
     print("Your answer is correct!")
     i13b=i13b+1
else:
     print("Your answer is incorrect!")
     print("The correct answer is Playing Cards.")
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 4")
print()
print(" In 'Call of Duty: Advanced Warfare,' what's the name of Jack Mitchell's best friend?")
a11b=input("Enter your answer: ")
print()
if a11b=="Will Irons"or a11b=="will irons":
     print("Your answer is correct!")
     i13b=i13b+1
else:
     print("Your answer is incorrect!")
     print("The correct answer is Will Irons.")
      
print()
input("Please enter to continue to the next question.")
print()
print()
print("Question 5")
print()
print("Who is the first character you play in 'Injustice 2?'")
a11b=input("Enter your answer: ")
print()
if a11b=="Batman"or a11b=="batman":
     print("Your answer is correct!")
     i13b=i13b+1
else:
     print("Your answer is incorrect!")
     print("The correct answer is Batman.")
print()
print("Your score in the Fill in the Blank segment is",i13b,"out of 15 marks")
print()
print("Your total score is ",i13a + i13b,"out of 25!")
print() 
print("The trivia is over!")
print("Thank You")



